# Privacy Policy for SeenMatch: Last Seen Alert

Effective date: May 10, 2026

SeenMatch: Last Seen Alert (“SeenMatch”, “we”, “our”, or “the app”) respects your privacy. This Privacy Policy explains what information the app uses, how it is handled, and what choices you have.

## 1. What the app does

SeenMatch helps users analyze visible online and last-seen activity for selected Telegram contacts. The app is designed to compare activity patterns only for people selected by the user.

SeenMatch does not read, access, store, or analyze Telegram messages, chats, media, call history, or hidden private data.

## 2. Information we may process

The app may process the following information:

- Telegram phone number used for sign-in
- Telegram authentication status
- Selected Telegram contact identifiers and display names
- Visible online / last-seen status information
- Local activity logs generated by the app
- App usage events
- Crash and diagnostic information
- Purchase and subscription status when Premium is enabled

## 3. How information is stored

Selected contact data, activity logs, and tracking information are stored locally on your device using a local database.

We do not sell your personal data.

## 4. Firebase Analytics and Crashlytics

SeenMatch uses Firebase Analytics to understand basic app usage and Firebase Crashlytics to detect crashes and improve app stability.

These services may collect device information, app usage information, crash logs, diagnostics, and similar technical data.

## 5. Telegram access

SeenMatch uses Telegram connection only to read visible online and last-seen status information available to your own Telegram account.

The app does not read your Telegram messages, private chats, media, files, or hidden information.

SeenMatch is not affiliated with, endorsed by, or sponsored by Telegram.

## 6. Premium subscriptions

SeenMatch may offer Premium features through subscriptions. Subscription processing may be handled by Google Play and RevenueCat.

RevenueCat may process purchase identifiers, subscription status, entitlement information, and related transaction data to manage Premium access.

## 7. Notifications

If you enable alerts, SeenMatch may send local notifications when selected activity conditions are detected. You can disable notifications from your device settings or inside the app where available.

## 8. Children

SeenMatch is not intended for children under 13. The app is intended for users who are allowed to use Telegram and Google Play services in their country.

## 9. Data sharing

We do not sell user data. Data may be processed by third-party service providers used by the app, including Firebase, Google Play, and RevenueCat, only for app functionality, analytics, crash reporting, and subscription management.

## 10. Data deletion

You can delete app data by uninstalling the app or clearing the app’s storage from your device settings.

If you need assistance regarding your data, you can contact us at:

icebreakerstudios.app@outlook.com

## 11. Changes to this policy

We may update this Privacy Policy from time to time. Updates will be posted on this page with a new effective date.

## 12. Contact

For questions about this Privacy Policy, contact us at:

icebreakerstudios.app@outlook.com
